env:
  global:
  - secure: NLD/m9Q/NRSHnsrCowe0v8dM3dhwjwp5wYRvUIWeNXd3APZnJCGU/RLQPzaCB7+sosWDhkam+7fGCoeH7Guy1dmgTEHbcwFsT16ZsP2LVvUo/0gjX1QcbdB3vefv5QTeF4AepyogdYkRq71J8QlQioCfhjN+bexRTij0MdLf5Aavwio6DCV7lfuR8wd0vWHLUUOys9Deuz4J/PtwFW8xZuLk4FZv95xmUfFBp66JyLLwXaMJU2YUFFxEk7VlMAceE2UoHqcncjKwX69Y77DRPD/qsIGh6MRHk6RwhTAR4kkAZIeK2YFmFrCNe/BQ0qrHvnA8mH8W+xYXSXvtgmX0deA+a3G2ixb4C0s+Q0/YuuXdZexpSk/X0L1e0z92hlpI8TnE3v917w7qzDiPqXJCnlNIapsIhhAZKPw7bPGLNxllNrPmfntdCxGUEszi9PzblC+RPGyS5CTm21NOhX3xfdKLEec/ESW+n8zQdroiHgndHpXAK8JbNhy31/s0mH9yBN7Vn9tEhm/t/V4UfG/TYduY4t4//ISbrTYIzns82l9e5raJKHmjAqCuoQHy0dB1fwCMqiIeJqyQl/ZMMHoP9GTr1BMpQBQ6KgmO7CPQJJy6RwDBzy5Pf578vIMnQFXGH3vbLhSRSW4JwehYyACR4+q6ysQHfShBaPSEfNYg7lk=
  - secure: gSxfGLnDbeUfbV6w+0WqwHZJn7sM+un6MRjneZztQy3aThi1JsT9sn9sc053M+ejIsrYQ0U5fPPal2Q3WxRygcZKYWAdiCGwGqFAcLE5eAM85ra+8sP5UY0xxtXbpM4l9IcxcqXHhJWcqhcbFk7PyotEdzOdK4+9m0a5YG0OIurpgRsnRWqtm5k+HxeeC46q51+ki8h3bhis7rPx/VgQ1Tef+1q37xbzOnSnknnOqLgkRMnxJQsvi2Vh8nHf4lwPD/zCk9/3nKGtyq8A7qmh/LAU8NaEKDsM4tTBRySjG7BLk0qVV36p68IjYI4ICk1mvoXQltRDBr1QW3mjipoMc/hBk9KhEkq3Sv7Wg1ML2WY7sTD0Ki7Ry3woGXOK5S6UJRHU9Rr6Ki5bCdmC54OeDeC6ABCSqgVdQkfuBqNOnLBHA9HO97SbalOE6IK8CvDOx/85IvrnvyQK2G6YyZ5Guly56muZR+anll2fY2n1xeQB+0Qmbw/zDyHmFGBaLe6/kSToLwQwYEGOc0AC4/zF3K80WKc6wWnoggb+mCNTLOut9yLk01FTpIs7eGKBmk9EtoF49GTMjuGBaJ8Lct1w1s8tyjEu+0AQuQ6C8tl6vo12YGwBwieyrWkqG3LNNI4ITkpFgwkL/qVApieKabvy0rprU4sWCnQ+KFjEytqN23c=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: mitclfc9BVkvaJHkweV/Bjk9b2OQhM8CbQ1CuxNIswNnDatLGBP2skbi4hcKTqo9z5sSSeLtZN3x5A7MD7PaGGzmY2NvP6td0jVTfZHs5IKd3EsTEAG+/ujqX9Iip6JqmtKYR6mrBU39NBesZH7IiZPdnxsksvHT0/LEfE+pg1AexCr4sCXaSSlYuKEDQKlnppeC/8C+DMK5OV2GTFPC8+nZzbCfedK1mZoCFx2jWcQtc5bES5yCDSd1E1e28iaJ9dPBDjfGo9fBmx1gztGBuH1QgNfQ53FxC4q3EIw5pyvPudNtdxS8zr9tRw3Io2sx6faaEDXkRd05KCwXl4V7CsbkJYFbannQWQgxYaoO/GMB1e/XLYqYInon3/caDUGN/VOvBMVcrf3JHLxC5F703PkUAQ6Um4Zbeq06MMWgffYUWUyLMugAk7wc12ww6O4SHMceF+WzxTNvJrs60s56mpuZ99HLktUQtyQDeVfbzqgXKE9A0nYJuC1aRgzjROb8OfN1DupEVk2R4CZn/4tZLy9NsD2c3wQsrWHxdfeapnT7ELoa7CCaB+pyZyQyahbHTfzgej5wDPSJ9udt7wjjhT2RK3cx5068L7SmI6XMdvqRYSsMY2AtrOzdQBkb6cwHawtEy/IN7pmO664tlEwi//Yk095xhoBEhjYnvEraohU=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull sguellec/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t sguellec/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: rXSvRIUcQ4iTiL2QJHHHrb9Fq2I/iJ3hqzN0jvGN44peSPY0SsueaQAYsNd26kOuT2ppuSu/0nUVXIeqmtF3tIcfggxAYRzlDheZu0vcyWGO3C1bFNa+Dc3w+pNEa0zBFBdJpeqzXOojUzzDsiUwyVz8168wl9UaA08nF7Xtjuke0INccmSb97gyIUUgaFEV01JeMWzd75RaArXDY5EPuCTg1IXf2bEj8BuffwQtkGmqzm0ckZienRwbLdMk0ILi/TZTr0c0N9IuxDNsojNEiNsz1IrqmKmRd4Usm7pmz1NF5vhUqkxgek3Nw4nCVodnV2ZveYd3hoTV/xV9XBQVy7lvuZ3/PlLq7pteNo0LVlMZ6HpKj6hqu725HBGm6W5CGHrDhYCPfN7bZbmP1h7TjvCueAmDKyUqKO+ELNySt5bduPM9r6aoJWkB/VWlDhVKSCddMyXOrN3UNQ9R0hp40dUULs3t+fsFAKNciV8lpAJUc3ktdpfEMwT+a4aHDQRfvex/qpw+HNvrm8itBU2jBPEbPYNiFeD4Qg8kHlZ4yviYsHC66PbQdtC76pUA88T7nVR4onOQsdlx1Y+fnHTCd29RvFS1pgnveaIMZtsosCCMAV9taLbl6h1Cv4UdxaQ38rhirKuN7aFkKBxLlfV93iiGZfkRWTkXZ9J++GVJ4OA=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
